version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: speedway_alamanc_container
        ports:
            - '5432:5432'
        volumes:
            - progresDB:/var/lib/postgresql/data
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
volumes:
    progresDB:
