version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: speedway_alamanc_container
        ports:
            - '5432:5432'
        volumes:
            - progresDB:/var/lib/postgresql/data
        env_file:
            - ./.env
volumes:
    progresDB:
